# Basic Word2Vec w/ Pretrained Google Model

In [9]:
from gensim.models import word2vec
from gensim.models import KeyedVectors

import warnings
warnings.filterwarnings('ignore')

# Load model

In [3]:
path = "/Users/allen/Projects/cmsc723/homeworks/dan/GoogleNews-vectors-negative300.bin"
model = KeyedVectors.load_word2vec_format(path, binary=True)

# Sample Tasks

View a sample word embedding

In [4]:
model["dog"][250:]

array([-0.23144531,  0.16601562, -0.21386719, -0.0703125 , -0.07568359,
        0.19628906, -0.12988281, -0.10595703, -0.35351562, -0.11669922,
       -0.05102539,  0.03393555, -0.14355469, -0.00390625,  0.17382812,
       -0.09960938, -0.16601562, -0.08544922, -0.3828125 ,  0.05908203,
       -0.06225586,  0.08837891, -0.08886719,  0.328125  ,  0.06835938,
       -0.19140625, -0.00083542,  0.10400391,  0.15234375, -0.00153351,
        0.41601562, -0.03320312,  0.14941406,  0.2421875 , -0.17675781,
       -0.04931641, -0.12451172,  0.12597656,  0.17480469,  0.28125   ,
       -0.18066406,  0.10302734, -0.27539062,  0.26171875,  0.24609375,
       -0.04711914,  0.0625    ,  0.41601562, -0.35546875,  0.22265625],
      dtype=float32)

Find similar words

In [10]:
model.most_similar("woodworking")

[('carpentry', 0.7538774609565735),
 ('woodshop', 0.7094520330429077),
 ('woodcarving', 0.7084826827049255),
 ('Woodworking', 0.6944210529327393),
 ('cabinetmaking', 0.6722680330276489),
 ('tinsmithing', 0.6697934865951538),
 ('woodturning', 0.667036771774292),
 ('wood_carving', 0.6637512445449829),
 ('woodworking_shop', 0.6599881649017334),
 ('woodworker', 0.6565081477165222)]

Fun with vectors

In [11]:
model.most_similar(positive=['woman', 'king'], negative=['man'], topn=2)

[('queen', 0.7118192911148071), ('monarch', 0.6189674139022827)]

Find what doesnt belong

In [12]:
model.doesnt_match("breakfast cereal dinner lunch".split())

'cereal'

In [13]:
model.doesnt_match("carp tuna shark monkey".split())

'monkey'

# Load into Torch embeddings object

In [28]:
import torch.nn as nn
import torch

In [27]:
embeddings = nn.Embedding(*model.vectors.shape, padding_idx=0)
# embeddings.load_state_dict({'weight': model.vectors})


In [29]:
embeddings.weight.data.copy_(torch.from_numpy(model.vectors))

tensor([[ 0.0011, -0.0009,  0.0003,  ..., -0.0016, -0.0001, -0.0001],
        [ 0.0703,  0.0869,  0.0879,  ..., -0.0476,  0.0145, -0.0625],
        [-0.0118, -0.0474,  0.0447,  ...,  0.0713, -0.0349,  0.0242],
        ...,
        [-0.0197, -0.0908, -0.0194,  ..., -0.0164, -0.0134,  0.0466],
        [ 0.0327, -0.0322,  0.0361,  ..., -0.0089,  0.0270,  0.0190],
        [ 0.0452, -0.0452, -0.0039,  ...,  0.0796,  0.0723,  0.0130]])

In [70]:
sentence = "the quick brown fox jumped over the lazy dog"
indexes = [model.vocab[w].index for w in sentence.split()]
embeddings(torch.LongTensor(indexes))

tensor([[ 0.0801,  0.1050,  0.0498,  ...,  0.0037,  0.0476, -0.0688],
        [ 0.3242,  0.0137, -0.0282,  ...,  0.0518, -0.0903, -0.1279],
        [ 0.0079,  0.1289,  0.0273,  ..., -0.0137,  0.1206,  0.1924],
        ...,
        [ 0.0801,  0.1050,  0.0498,  ...,  0.0037,  0.0476, -0.0688],
        [ 0.1992,  0.0454, -0.0732,  ..., -0.1777,  0.0400,  0.0515],
        [ 0.0513, -0.0223, -0.1729,  ...,  0.4160, -0.3555,  0.2227]],
       grad_fn=<EmbeddingBackward>)

In [47]:
model["cat"][:10] == model.vectors[model.vocab["cat"].index][:10]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [69]:
word2ind = {k: v.index for k,v in model.vocab.items()}
word2ind["cat"]

5947